### ISSUE TITLE
when single cpu , run systemctl status irqbalance make io read very high

### ISSUE THREAD

**Issue by cyrnotcry** [Irqbalance/irqbalance#103]
12964 be/4 root      105.81 M/s    0.00 B/s  0.00 % 99.53 % systemctl status irqbalance.service

it can stop run,but shoudn‘t make io so high

**Comment by nhorman** [comment]
thats the output from iotop showing the the io throughput of systemctl, not of irqbalance.  If you really think you have a bug in irqbalance, show me:
1) The iotop output of the irqbalance process
2) the version of irqbalance that you are running
3) an strace of irqbalance while that high load is happening
