### ISSUE TITLE
In some arch, A package may have more than one numa

### ISSUE THREAD

**Issue by Pyxisha** [Irqbalance/irqbalance#104]
Irqbalance  think a numa  always have more than one package(cpu socket). In some arch(arm64), this is not always true. actually this can be controlled by bios. :

![image](https://user-images.githubusercontent.com/33088063/60883191-1b596a80-a27c-11e9-9c81-1d1e5758b57c.png)

in such situation, some numa will have no packages, and irq in that numa can not be balanced.
currently, we develop such a patch to avoid the problem. is there a better solution?
[patch.txt](https://github.com/Irqbalance/irqbalance/files/3372637/patch.txt)

**Comment by nhorman** [comment]
yes, you should modify  the place_irq_in_node function to inspect irq_numa_node(info)->mask.  If the mask for the preferred node is 0 (no cpus set), assign the irq to the unspecified node (id -1) instead.

**Comment by Pyxisha** [comment]
thanks, I'll try it.

**Comment by Pyxisha** [comment]
sorry, I mistake it,  this bug has been fixed in https://github.com/Irqbalance/irqbalance/commit/7bc1244fbf4cbc41cfdaf5583e2bcf6f50d53c88
