### ISSUE TITLE
add_new_irq may override irq's balance_level

### ISSUE THREAD

**Issue by Pyxisha** [Irqbalance/irqbalance#105]
Currently user-defined policies against non-PCI devices' interrupts
are not working properly.

For example, when trying to set "balance_level=core" for a non-PCI
device interrupt which is classified as "other", will result in
the level of "package" because overrided in add_new_irq().

policyscript:
#!/bin/bash
echo balance_level=core

--debug
[strace.txt](https://github.com/Irqbalance/irqbalance/files/3376357/strace.txt)

I analysised the code， it seems in add_new_irq, irq's level are assigned correctly in add_one_irq_to_db(NULL, irq, &pol);. but are override at the end of add_new_irq. I'm quite confused about the code, why balance_level are reassigned here?

**Comment by nhorman** [comment]
Its a holdover from before  we created the policy mechanism.  It looks like the hint information should be passed into add_one_irq_to_db, and the hint information should be used to set class if get_irq_class returns < 0, and the level information should be assigned if pol->level is > 0.  

Feel free to send a patch for it

**Comment by Pyxisha** [comment]
thanks， I’ll try it.
