### ISSUE TITLE
why pointer to sleep_interval are pass to scan 

### ISSUE THREAD

**Issue by Pyxisha** [Irqbalance/irqbalance#108]
I'm quite confused about these a few lines in irqbalance.c

	if (data != &sleep_interval) {
		data = &sleep_interval;
		g_timeout_add_seconds(sleep_interval, scan, data);
		return FALSE;
	}

	int *last_interval = &sleep_interval;
	g_timeout_add_seconds(sleep_interval, scan, last_interval);

why the address of 	sleep_interval are passed into scan? is there any condition that data != &sleep_interval can be true? I guess these lines are considering that sleep_interval can be modified by socket, is this right? but why the address of sleep_interval and not the value of sleep_interval are passed?

**Comment by nhorman** [comment]
you're right, the whole thing is vestigual.  We will never fall into that condition, but it doesn't matter because the glib library will continue to run the scan at n second intervals until we receive a SIGINT signal, which causes the loop to exit.  This entire clause should be removeable

**Comment by Pyxisha** [comment]
in irqbalance.c line 408

				if (new_iterval >= 1) {
					sleep_interval = new_iterval;
				}

sleep_interval maybe set to a new value, when sleep_interval are changed, do we need to add a new interval event and return False?

**Comment by nhorman** [comment]
thats broken, just setting a new value for sleep_interval doesn't change the value of the pointer, so the comparison still returns false (I should never have merged the irqbalance ui code).  If you want to fix that, we should stop comparing the value of data to &sleep_interval, and instead compare sleep_interval to some interim ui-set new_sleep_interval value and if they don't match, then update the g_timeout_add_second function.
