### ISSUE TITLE
v1.0.4-10 (x86_64) - memory leak - CentOS 6.6

### ISSUE THREAD

**Issue by rzpld4** [Irqbalance/irqbalance#13]
Running CentOS 6.6 on Linode (Xen), fully patched and using irqbalance-1.0.4.-10.el6.x86_64. The IRQBALANCE seems to leak about ~60MB/day. The server is running 4 vCPU under Xen. 

CentOS 6.6 (final)
kernel 3.16.5 x86_64 SMP

**Comment by grahl** [comment]
I have the same issue on CentOS 6.6 and have now resorted to the cron job as rzpld4 did since I was unable to reformat the patch linked above so that it would compile cleanly to 1.0.4, if anyone can supply that I'd be happy to test it. I reported the issue to CentOS here http://bugs.centos.org/view.php?id=8042

**Comment by rzpld4** [comment]
I'm not certain whether CentOS team would update irqbalance independent of Red Hat doing it first, but good idea to report. 

I have irqbalance v1.0.8 running and can send you the binary if you would like. It's been running stable for a couple of weeks now.

**Comment by dieskim** [comment]
rzpld4 - I would love to have the binary as well... 

I added a bug report to Red Hat - https://bugzilla.redhat.com/show_bug.cgi?id=1178247#c0

**Comment by rzpld4** [comment]
I've uploaded the IRQBALANCE v1.0.8 binary to http://wikisend.com/download/616260/irqbalance.gz, it was compiled from source on GITHUB on CentOS 6.6 X86_64. It has been running stable for my on 4 x vCPU at Linode. The file will be available for 30 days

**Comment by rzpld4** [comment]
Thank you for posting the bug reports, lets hope the distros will pull and update for the next release.

Happy New Year!

**Comment by nhorman** [comment]
The process to report issues to distros is distro specific.  For red hat, you can open a 
bugzilla at bugzilla.redhat.com or open a support ticket with your account manager.  I expect there is a similar process for CentOS
