### ISSUE TITLE
Is irqbalance useful with newer kernels?

### ISSUE THREAD

**Issue by paride** [Irqbalance/irqbalance#151]
In Debian it has been reported [1] that newer kernels (at least >= 4.19) are natively able to do the IRQ balancing, and that having irqbalance running at the same time can cause more harm than good.

As the maintainer of the irqbalance Debian package I'd like to better understand this issue to give proper hints to the users and possibly discourage the installation of irqbalance with the newer kernels. While I maintain the package I am not fully familiar with the balancing mechanisms, so I'd like to ask you:

 - Are there cases where irqbalance does improve on the kernel balancing?
 - Should we discourage the installation or irqbalance with newer kernels?

Thanks!

[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=926967

**Comment by nhorman** [comment]
I assume you're referring to the in-kernel affinity computation code that hellwig and and Gleixner wrote?  Yeah, it attempts to do some intellegent spreading of irq vectors for msi[x] interrupts, and pretty well embodies the default policy for irqbalance.  That said:
1) There should be no conflict  with running irqbalance.  That is to say, if you overwrite the irq affinity from user space, it should let you do that, and the irqbalance computation should be equivalent from a performance standpoint to the in-kernel version.  If the kernel attempts to overwrite the user provided affinity masks, thats a bug in the kernel, and if the performance of the irqbalance provided masks is less than the kernel provided masks, thats a bug that needs addressing in irqbalance

2) The kernel policy is driver centric.  That is to say the driver requesting the interrupts selects affinity that (ostensibly attempts to optimize throughput for that device).  That makes sense in isolation, but doesn't in any way take into account desired administrative policy.  I.e. what if a user wants to dedicate a cpu to a high prority user space tasks that doesn't want to take time to process interrupts, or perhaps you only want to handle network traffic on a certain subset of cpus.  For that you need more flexible policy, and the in-kernel affinity scaffolding doesn't do that, you still need irqbalance for those non-default use cases.

So the long and the short of it is - if you are ok with the default kernel affinity selection policy, yes, you could turn off irqbalance, but turning it on shouldn't hurt anything (if it does, its a bug), and if you don't have a standard performance environment, you still need irqbalance
