### ISSUE TITLE
configure failed when I trying to build 

### ISSUE THREAD

**Issue by leoliu-taishan** [Irqbalance/irqbalance#152]
checking for numa.h... no
checking for getopt_long... yes
checking for numa_available in -lnuma... no
checking for floor in -lm... yes
checking for pkg-config... /usr/bin/pkg-config
checking for GLIB2... no
configure: error: glib-2.0 is required

#yum install glib
Last metadata expiration check: 2:40:00 ago on Thu 04 Jun 2020 03:59:25 PM CST.
No match for argument: glib
Error: Unable to find a match: glib

At my linux system: no glib, only have glibc
#rpm -qa | grep ^glib
glibc-common-2.17-260.vendor.x86_64
glibc-headers-2.17-260.vendor.x86_64
glib2-2.56.1-4.vendor.x86_64
glibc-devel-2.17-260.vendor.x86_64
glibc-2.17-260.vendor.x86_64

**Comment by nhorman** [comment]
The glib2 runtimes are right there in your list:
glib2-2.56.1-4.vendor.x86_64
you need glib2-devel installed as well, so the pkg-config file and glib2 headers are installed
