### ISSUE TITLE
Unknown key name 'Environmentfile' in section 'Service', ignoring.

### ISSUE THREAD

**Issue by DevDorrejo** [Irqbalance/irqbalance#153]
![image](https://user-images.githubusercontent.com/7697566/83988837-7a9f7f00-a912-11ea-8bc7-327afa157612.png)

hello i am using opensuse tumbleweed, last snapshot and i got this warning, what can be?

**Comment by nhorman** [comment]
Typo in the spec file, Environmentfile should be EnvironmentFile.  Just fixed it as part of commit 3a19387fb712c509f8137f06dbf899350ad2f84c
