### ISSUE TITLE
Suggestoion on how to make the NAPI SoftIRQ follow irqbalance "commands"

### ISSUE THREAD

**Issue by vladzcloudius** [Irqbalance/irqbalance#154]
After watching the https://www.youtube.com/watch?time_continue=129&v=hjMWVrqrt2U&feature=emb_logo I have a suggestion on how to relatively easy force the SortIRQ follow its HardIRQ (which in line follows the new config in `smp_affinity`) 

If there would be an API to force the corresponding NAPI out of the polling mode - it would do the trick, since the next time it would already be scheduled on the "correct" CPU.

**Comment by nhorman** [comment]
not really sure what you're asking for here.  The default behavior for softirqs is to be triggered on the same cpu that the irq was generated on.  If you switch irq affinity while the napi state for that queue is still scheduled, it won't follow the irq immediately, but its run time is limited to its napi budget (set net_rx_action).  If it drains the hardware queue, the napi poll for the queue will be disabled, and the next interrupt will occur on another cpu based on the new irq affinity, and the corresponding softirq will happen there.  The only way that doesn't happen is if the network interface is so busy that the napi poll never manages to complete, but if thats the case, you should never get another interrupt from the device again, and the cpu in question should be 100% pinned in utilization.  You're not seeing some situation like that, are you?

**Comment by vladzcloudius** [comment]
> not really sure what you're asking for here. The default behavior for softirqs is to be triggered on the same cpu that the irq was generated on. If you switch irq affinity while the napi state for that queue is still scheduled, it won't follow the irq immediately, but its run time is limited to its napi budget (set net_rx_action). If it drains the hardware queue, the napi poll for the queue will be disabled, and the next interrupt will occur on another cpu based on the new irq affinity, and the corresponding softirq will happen there. The only way that doesn't happen is if the network interface is so busy that the napi poll never manages to complete, but if thats the case, you should never get another interrupt from the device again, and the cpu in question should be 100% pinned in utilization. You're not seeing some situation like that, are you?

I'm talking about the second case and, yes, normally when the NIC constantly has work to do beyond the NAPI budget NAPI will stay in the polling mode with disabled interrupts till the backlog is completely processed. And, yes, all this time it'll spin on the same CPU where there original HW interrupt got triggered. 

But what if you'd like to "move" it to a different CPU for any reason and can't wait till all backlog is processed because, for instance, you know that the load is not going to drop any time soon and because you have 2 HW queues pollers spinning on the same CPU killing it and you'd like to move them apart to different CPUs?

This question was asked during the presentation above and IMO it makes a lot of sense.

So, my proposal suggests a solution: if you can somehow tell the NAPI that *despite it having more work to do* it should fall back to the interrupt mode.

It would require patching NIC drivers obviously too since NIC interrupt machinery is re-enabled from the driver (right after they call for napi_complete(...)) and you'd have to "tell" them that they need to "complete" unconditionally.

To clarify, it's not that I have an issue - just trying to address the problem that was discussed during the presentation.

**Comment by nhorman** [comment]
I suppose it makes some sense, but a few notes:

1)  This isn't an irqbalance problem, its a problem that needs to be addressed in the kernel (as you noted), this isn't really the forum to address this.

2) Theres no real new api need to user space.  My first thought would be to have net_rx_action detect if there had been an irq affinity change, and complete the napi poll if its occured, to give the driver the opportunity to issue another interrupt.

3) I have a hard time believing this is a super big problem.  It takes alot of effort for a single queue to saturate a cpu, so unless you can illustrate that this is a significant problem, and kernel change is not highly likely

4) theres already an administrative solution to this problem (though less optimal), just ifdown/ifup the interface.  That will force the napi poll to complete and fix this problem without any kernel changes
