### ISSUE TITLE
Allow env variable to ban cpus using the cpulist syntax

### ISSUE THREAD

**Issue by ChanderG** [Irqbalance/irqbalance#160]
I have added code here (https://github.com/ChanderG/irqbalance/commit/677b686e223c74e64f5b230bdb4079555a5a62a9) to basically allow the cpulist syntax ("23", "40-49") to ban cpus from an environment variable.

The existing env variable IRQBALANCE_BANNED_CPUS with the hexadecimal mask is a bit cumbersome to use.

If there is interest in this feature upstream, I can open a PR.

**Comment by nhorman** [comment]
yeah, sure, seems reasonable.  Please open a PR
