### ISSUE TITLE
Re-add affinity_hint to support balancing irqs within cpu partitions

### ISSUE THREAD

**Issue by hejingxian123** [Irqbalance/irqbalance#171]
In the  current irq balance method, we can only limit the irq balancing range with specified numa node. When there exists various devices, the irq handlers' process time will be very different, and their real-time requirements will also be different. In our products, we need the various devices can bind to various cpu partitions. If re-add the affinity_hint feature, the devices can specified the irq balancing range by specified cpu partition which corresponding to the affinity_hint cpu mask.

I have read the rejected reason in https://github.com/Irqbalance/irqbalance/issues/68. I think that the policyscript approach cannot satisfy my above demands.

**Comment by nhorman** [comment]
Sorry, I'm not re adding affinity hint, it caused far too many issues.  I also dont see how policyscript cant satisfy your needs.  It allows for the overriding of numa node, and can easily be expanded to do just about anything,  including specifying a complete balance mask
