### ISSUE TITLE
ethernet related interrupts are assigned to different NUMA node

### ISSUE THREAD

**Issue by aram-father** [Irqbalance/irqbalance#175]
Dear developers,
I appreciate your wonderful tool balancing interrupts conveniently.

I have a question about an interrupt balancing policy.
I thought that `irqbalance` never assigns an interrupt to NUMA node where different with where the device is installed.

As you can see in the attachment below, my NICs, `enp4s0`, `enp5s0`, are installed NUMA node 0.
However, when I check `/proc/interrupts` I could see core 48(which is in NUMA node 1) is servicing ethernet interrupt massively.

Could you please let me know, the exact principles of `irqbalance`?

I've attached some files you mentioned at README.md as below:
- **Irqbalance version I've been using:** `irqbalance version 1.3.0`
- **/proc/interrupts output:** [proc-interrupts.txt](https://github.com/Irqbalance/irqbalance/files/6146107/proc-interrupts.txt)
- **irqbalance --debug output:** [irq-balance-debug-1m.txt](https://github.com/Irqbalance/irqbalance/files/6146108/irq-balance-debug-1m.txt)
- **content of smp_affinity files:** [smp-affinity-files.txt](https://github.com/Irqbalance/irqbalance/files/6146109/smp-affinity-files.txt)
- **my hw hierarchy:** [lstopo-no-graphic.txt](https://github.com/Irqbalance/irqbalance/files/6146111/lstopo-no-graphic.txt)

**Comment by nhorman** [comment]
irqbalance 1.3.0 is fairly old, the latest version is 1.7.0 and has several numa affinity fixes.  Can you build with the latest version and confirm that you still see the problem?

**Comment by nhorman** [comment]
closing, due to lack of response
