### ISSUE TITLE
libcap-ng used by "/usr/sbin/irqbalance" failed due to not having CAP_SETPCAP in capng_apply

### ISSUE THREAD

**Issue by SebDanielsson** [Irqbalance/irqbalance#182]
I'm running Fedora 34 and noticed this error in the journal:
libcap-ng used by "/usr/sbin/irqbalance" failed due to not having CAP_SETPCAP in capng_apply

Any idea how to fix this?

**Comment by nhorman** [comment]
Probably the updated libcap requires that I explicitly clear that capability.  I'll look shortly

**Comment by nhorman** [comment]
Its odd, I can see that the error occurs when I start the irqbalance service from systemd, but if I rebuild the upstream tree manually and run it, the error doesn't occur.  I wonder if the libcapng got updated right before shipment, and dependent applications might need to be rebuilt in response.  A quick search through bugzilla suggests libvirt and virsh are having simmilar problems.  Suggest opening a bug against fedora34 irqbalance asking for a rebuild.

**Comment by stevegrubb** [comment]
This problem is caused by NoNewPrivileges=yes in irqbalance.service. There's no need for that since the program correctly drops capabilities.

**Comment by nhorman** [comment]
@stevegrubb But why would you consider it an error to not have a cap for an app that doesn't need it.  In the case of irqbalance, we're just dropping all of our capabilities, when all capabilities were already dropped by systemd.  That doesn't seem like a cause to flag an error.

**Comment by stevegrubb** [comment]
The call to prctl fails due to EPERM, I need to pass this failure back to the calling program. Previously, we were silently eating the error which is the root of the problem. Some people needed to know that the bounding set is not what they expected. Programs that do check the return codes now have an error to deal with. But because irqbalance does not check the return codes of capng_apply, you won't notice anything. The code in the program is correct, I'd just drop the systemd option.

**Comment by stevegrubb** [comment]
Another fix, if you wanted to leave the systemd option, is to change to calling capng_apply with CAPNG_SELECT_CAPS instead of CAPNG_SELECT_BOTH.

**Comment by nhorman** [comment]
@stevegrubb thanks man.  Currently we are ignoring the return code, its just the log message thats the issue here.  I'll drop the NoNewPrivs from the systemd unit

**Comment by ryncsn** [comment]
This issue still presents with the latest Fedora & irqbalance.

**Comment by adatum** [comment]
Still present in Fedora 35 and irqbalance v1.7.0-8.fc35.x86_64

It seems the fix merged above is not yet included in a release? The current latest release (v1.8.0) of irqbalance is from April 2021.

**Comment by nhorman** [comment]
open a bug against fedora in bugzilla, requesting the update

**Comment by adatum** [comment]
@nhorman There is an existing Fedora [bug report](https://bugzilla.redhat.com/show_bug.cgi?id=1952715) but the latest comment is that an unreleased build with the latest irqbalance v1.8.0 still has the issue. 

Is there an irqbalance release which includes the merged fix?

**Comment by nhorman** [comment]
there is not, generally speaking I don't time releases to any particular distributions needs (I'd be releasing every week if I did).  The expectation is that, if a given distro can't wait for an updated upstream release, they backport the specific fix into their local build.  Thats what rpm is for :)

**Comment by adatum** [comment]
@nhorman Ok, thanks for fixing the issue. I'll pass the message along about backporting it.

**Comment by tanvp112** [comment]
This issue has re-appear with:

> Linux fedora 6.9.4-100.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Jun 12 13:37:46 UTC 2024 x86_64 GNU/Linux

> Jun 18 09:09:47 fedora /usr/sbin/irqbalance[903]: libcap-ng used by "/usr/sbin/irqbalance" failed dropping bounding set due to not having CAP_SETPCAP in capng_apply

Possibly a regression?

**Comment by nhorman** [comment]
are you building with the latest irqbalance, or using the fedora package?  If the latter you need to start by opening a bug with RH
