### ISSUE TITLE
ui/ui.c:17: possible missing comma ?

### ISSUE THREAD

**Issue by dcb314** [Irqbalance/irqbalance#184]
ui/ui.c:17:4: warning: suspicious concatenation of string literals in an array initialization; did you mean to separate the elements with a comma? [-Wstring-concatenation]

Source code is

                        "Gigabit Ethernet",
                        "10-Gigabit Ethernet,"
                        "Virt Event"};

Maybe better code:
                        "Gigabit Ethernet",
                        "10-Gigabit Ethernet",
                        "Virt Event"};

**Comment by nhorman** [comment]
Yeah, that's clearly a typo.  Go ahead and submit a patch please

**Comment by nhorman** [comment]
fixed it myseld
