### ISSUE TITLE
[bug] irqbalance-ui segfault or 'Invalid data sent.  Unexpected token:'

### ISSUE THREAD

**Issue by roman-orekhov** [Irqbalance/irqbalance#197]
On a machine with 80 cores and some 435+ IRQs I get these errors consistently on `master`, `v1.8.0` or stock Ubuntu 20.04.3 version of `1.6.0`. irqbalance-ui only started 5 times correctly from 50+ attempts, but then crashed anyway. (In all runs irqbalance itself was of version `1.6.0`).

Crashdumps say segfault happen [here](https://github.com/Irqbalance/irqbalance/blob/master/ui/irqbalance-ui.c#L307) (or on lines 304, 305, 308, etc.). After going through the code it appears that the protocol doesn't include telling clients how much data to expect. So irqbalance-ui just calls `recv` [once](https://github.com/Irqbalance/irqbalance/blob/master/ui/irqbalance-ui.c#L124) and hopes for the best while `recv` may not receive all the bytes really sent. A partial receive would of course cause such segfaults and unexpected tokens (I saw "DI", "SA", etc.)

I think the only _real_ solution is to change the protocol so that receivers would know when to stop receiving. Current data format doesn't allow to rewrite `parse`* functions into an online parser accepting partial input. However raising receive buffer to 38192 prevented crashes for now.

**Comment by nhorman** [comment]
I would imagine the most direct solution, without modifying the protocol would be to have the send side build the entire message, and send it in a single send call.  Then the receiver would get a MSG_TRUNC flag in the recv call that it could check and use to expand the size of the buffer until such time as the TRUNC flag was not set.  I'll try work up a patch

**Comment by nhorman** [comment]
https://github.com/Irqbalance/irqbalance/pull/198

Please build with the branch in that PR and confirm that the segfaults are mitigated

**Comment by roman-orekhov** [comment]
> I would imagine the most direct solution, without modifying the protocol would be to have the send side build the entire message, and send it in a single send call.

That's what irqbalance does [already](https://github.com/Irqbalance/irqbalance/blob/master/irqbalance.c#L459).

**Comment by nhorman** [comment]
please see the patch before you respond.

I misspoke in my previous comment.  You are correct, in that irqbalance sends the entire buffer as a single message (which is good), but the receiver doesn't set the MSG_TRUNC flag, and consequently never checks the length of the received message against the allocated length.  The patch fixes that

**Comment by roman-orekhov** [comment]
@nhorman 
gcc 9.3 failed:

```ui/irqbalance-ui.c: In function ‘get_data’:
ui/irqbalance-ui.c:108:2: error: a label can only be part of a statement and a declaration is not a statement
  108 |  int socket_fd = init_connection();
      |  ^~~
```

Also manual [says](https://linux.die.net/man/2/recvfrom):

> MSG_TRUNC (since Linux 2.2)
    For raw (AF_PACKET), Internet datagram (since Linux 2.4.27/2.6.8), netlink (since Linux 2.6.22) and UNIX datagram (since Linux 3.4) sockets: return the real length of the packet or datagram, even when it was longer than the passed buffer. **Not implemented for UNIX domain (unix(7)) sockets.**

**Comment by nhorman** [comment]
Ugh, ubuntu hasn't updated their compiler in forever, and older gcc doesn't allow placing labels before variable declarations.  Thats easily fixable.

As for the man page, That seems to be in conflict with what man (7) unix [says](https://man7.org/linux/man-pages/man7/unix.7.html).  Looking at the kernel sources, it would appear man 7 unix is [correct (since about 2012)](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=9f6f9af7694ede6314bed281eec74d588ba9474f)

Please repull the branch (I've fixed the patch to work on older compilers), and test again

**Comment by roman-orekhov** [comment]
> Please repull the branch (I've fixed the patch to work on older compilers), and test again

It works, thanks!

Now to make the program usable with this many cores and IRQs on a 1080p monitor I'd have to allow data scrolling using ncurses =/

PS: But still I would just `return get_data(string);` instead of `goto try_again;`

**Comment by nhorman** [comment]
ok, I'l merge this.  If you want to work up a patch to allow scrolling, I'll gladly take a look at it.
