### ISSUE TITLE
No information about --migrateval option in irqbalance

### ISSUE THREAD

**Issue by natesh-sharma** [Irqbalance/irqbalance#203]
irqbalance comes with the option "-migrateval", however, there is no information available about it.

Upon checking the source code I see the changes,

From irqbalance.c:

#ifdef HAVE_GETOPT_LONG
struct option lopts[] = {
        {"oneshot", 0, NULL, 'o'},
        {"debug", 0, NULL, 'd'},
        {"foreground", 0, NULL, 'f'},
        {"powerthresh", 1, NULL, 'p'},
        {"banirq", 1 , NULL, 'i'},
        {"deepestcache", 1, NULL, 'c'},
        {"policyscript", 1, NULL, 'l'},
        {"pid", 1, NULL, 's'},
        {"journal", 0, NULL, 'j'},
        {"banmod", 1 , NULL, 'm'},
        {"interval", 1 , NULL, 't'},
        {"version", 0, NULL, 'V'},
        {"migrateval", 1, NULL, 'e'},    <<------
        {0, 0, 0, 0}
};

static void usage(void)
{
        log(TO_CONSOLE, LOG_INFO, "irqbalance [--oneshot | -o] [--debug | -d] [--foreground | -f] [--journal | -j]\n");
        log(TO_CONSOLE, LOG_INFO, "     [--powerthresh= | -p <off> | <n>] [--banirq= | -i <n>] [--banmod= | -m <module>] [--policyscript= | -l <script>]\n");
        log(TO_CONSOLE, LOG_INFO, "     [--pid= | -s <file>] [--deepestcache= | -c <n>] [--interval= | -t <n>] [--migrateval= | -e <n>]\n");
}

No information is available in the man page too.

**Comment by nhorman** [comment]
fixed in commit 917b10268cf5c2a4a6b624b4bb9928e5e3fe2353
