### ISSUE TITLE
irqbalance never exits

### ISSUE THREAD

**Issue by andreas-schwab** [Irqbalance/irqbalance#214]
irqbalance fails to exit after SIGTERM because parse_proc_interrupts always sets need_rescan.  This happens because of this line in /proc/interrupts:

161:          0          0  48059000.gpio  25 Edge      button S2

**Comment by nhorman** [comment]
yeah, looks like the while (need_rescan | need_rebuild) { } loop needs to be augmented to be:
while (keep_going && (need_rescan || need_rebuild)) {}

I'm a bit tied up, can you submit a PR?
