### ISSUE TITLE
Unable to scroll under tui mode of irqbalance-ui

### ISSUE THREAD

**Issue by vishal14051992** [Irqbalance/irqbalance#217]
Hello,

I was testing irqbalance-ui and found that on my test system with 64 cpu, the tui
interface only lists till 58 cpu's, and there is no way I can scroll down in any of the tabs.

Am I missing anything here.

Here is reference image
https://i.imgur.com/c1AvSBG.png [F3 tab]
https://i.imgur.com/4VfJgvV.png    [F4 tab]
https://i.imgur.com/d23i5C7.png   [F5 tab]

I have tried every key, but scrolling is not possible.

**Comment by liuchao173** [comment]
You can use the latest code to test, if you have any questions, please comment.
