### ISSUE TITLE
[irqbalance-ui] F5 tab: Show range of cpus in cpulist for consecutive cpus

### ISSUE THREAD

**Issue by vishal14051992** [Irqbalance/irqbalance#224]
Hello Team,

I tested recent code and I can see that cpulist is moved to last column. It will be very user friendly if the tab only show cpulist range. For example, instead of below output for IRQ0,

NUMBER IS BANNED CLASS ASSIGNED TO CPUS

IRQ 0 NO Other 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47

it should show,

NUMBER IS BANNED CLASS ASSIGNED TO CPUS

IRQ 0 NO Other 0-15,32-47

This will save a lot of space and will provide more crisp output for large systems with 200+ cpus.

Thanks,

**Comment by liuchao173** [comment]
I'am doing this right now.
https://github.com/Irqbalance/irqbalance/pull/223

**Comment by liuchao173** [comment]
done
