### ISSUE TITLE
new release 1.9.1?

### ISSUE THREAD

**Issue by dirkmueller** [Irqbalance/irqbalance#231]
there were a few bugfixes in git since 1.9.0 release, time to release a 1.9.1?

**Comment by nhorman** [comment]
Yeah, we can do that.  @liuchao173 do you want to walk through the release process, or shall I handle it?

**Comment by dirkmueller** [comment]
@nhorman @liuchao173 any update?

**Comment by liuchao173** [comment]
I'm trying to do this. Please wait

**Comment by liuchao173** [comment]
done @dirkmueller
