### ISSUE TITLE
1.9.1: make check triggers a coredump on aarch64 & ppc64le

### ISSUE THREAD

**Issue by travier** [Irqbalance/irqbalance#241]
I'm packaging 1.9.1 for Fedora and running `make check` fails on `aarch64` & `ppc64le`:

- Scratch build: https://koji.fedoraproject.org/koji/taskinfo?taskID=93218877
- ppc64le: https://kojipkgs.fedoraproject.org//work/tasks/8932/93218932/build.log
- aarch64: https://kojipkgs.fedoraproject.org//work/tasks/8931/93218931/build.log

```
+ make check
Making check in tests
make[1]: Entering directory '/builddir/build/BUILD/irqbalance-1.9.1/tests'
make  runoneshot.sh 
make[2]: Entering directory '/builddir/build/BUILD/irqbalance-1.9.1/tests'
make[2]: Nothing to be done for 'runoneshot.sh'.
make[2]: Leaving directory '/builddir/build/BUILD/irqbalance-1.9.1/tests'
make  check-TESTS
make[2]: Entering directory '/builddir/build/BUILD/irqbalance-1.9.1/tests'
make[3]: Entering directory '/builddir/build/BUILD/irqbalance-1.9.1/tests'
../test-driver: line 112:  2701 Segmentation fault      (core dumped) "$@" >> "$log_file" 2>&1
FAIL: runoneshot.sh
============================================================================
Testsuite summary for irqbalance 1.9.1
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See tests/test-suite.log
============================================================================
```

**Comment by travier** [comment]
See https://src.fedoraproject.org/rpms/irqbalance/pull-request/6

**Comment by travier** [comment]
Sorry, I just had the time to report that to bring awareness as the release is fresh. I'll give you more info asap.

**Comment by dirkmueller** [comment]
very likely this is fixed by https://github.com/Irqbalance/irqbalance/commit/014765d947b3624db9d5591299ea315607733c3c

**Comment by dirkmueller** [comment]
@travier can you confirm the fix in prev comment?

**Comment by travier** [comment]
Thanks! Looks like it fixed the issue for me: https://koji.fedoraproject.org/koji/taskinfo?taskID=93461436
