### ISSUE TITLE
when sending SIGTERM (ie when stopping / disabling corresponding service) irqbalance does not stop

### ISSUE THREAD

**Issue by XavierMika** [Irqbalance/irqbalance#259]
Hi

One of the reasons for this issue is the combination of the fact that :

1/ thermal is enabled by default on x86_64 :
# Check whether --enable-thermal was given.
if test ${enable_thermal+y}
then :
  enableval=$enable_thermal;
else $as_nop
  if test x"$host_cpu" = x"x86_64"
then :
  enable_thermal=yes
else $as_nop
  enable_thermal=no
fi

2/ kernel option CONFIG_THERMAL_NETLINK is not activated

In this configuration init_thermal () doesn't return, so irqbalance is not working at all, 
> 1st call to nl_recvmsgs resulting (via handle_error) in this error:

thermal: received a netlink error (Interrupted system call should be restarted).

Please specify in the requirements that if the kernel version used is 5.9+ that the CONFIG_THERMAL_NETLINK option must be enabled on x86_64 or adapt configure.ac accordingly, thanks

**Comment by XavierMika** [comment]
well done, this change permits irqbalance to start but with these error messages :

thermal: received a netlink error (Interrupted system call).
thermal: failed to receive messages.
Failed to initialize thermal events.

**Comment by nhorman** [comment]
Looks like we need to be a bit smarter that  just returning NL_STOP.

I've made a PR here:
https://github.com/Irqbalance/irqbalance/pull/262

Please build that and test, it should correct both the hand and the error above

**Comment by XavierMika** [comment]
with the patch error messages are the same :

 thermal: received a netlink error (Interrupted system call).
 thermal: failed to receive messages.
 Failed to initialize thermal events.

**Comment by nhorman** [comment]
please run irqbalance under gdb and let me know what the value of err->error is in handle_error

**Comment by XavierMika** [comment]
value of err->error : -2

**Comment by nhorman** [comment]
I've updated the branch, please pull and test again

**Comment by XavierMika** [comment]
There is no more error message but we are back in the initial situation, no return from init_thermal

maybe this will be useful :
 init_thermal > establish_netlink > nl_recvmsgs
  first call of nl_recvmsgs : rc = 0
  2nd call of nl_recvmsgs rc : not returning

**Comment by nhorman** [comment]
Thats because I'm an idiot.  sorry, updated the branch, run one more time please

**Comment by XavierMika** [comment]
it is indeed better 

irqbalance works again, the two error messages remain:
 
thermal: failed to receive messages.
 Failed to initialize thermal events.

which I think are appropriate

**Comment by nhorman** [comment]
roger, thank you!
