### ISSUE TITLE
Is irqbalance processor C state aware when it does balancing?

### ISSUE THREAD

**Issue by asheeshr** [Irqbalance/irqbalance#260]
I saw in the release notes and commits for thermal integration. The notes and commits seem to suggest that processors that are disabled due to thermal constraints are now not considered for work allocation. However, for intermediate C states, are those factored into the balancing of the work load?

**Comment by nhorman** [comment]
It looks like the only updates to CPU banning occur when we receive a netlink message indicating that a current CPU reports 0 in its INDEX_PERF and INDEX_EFFI attributes.
