### ISSUE TITLE
irqbalance shouldn't run in containers (and maybe VMs?)

### ISSUE THREAD

**Issue by BryanQuigley** [Irqbalance/irqbalance#27]
Forwarding from here: https://bugs.launchpad.net/debian/+source/irqbalance/+bug/1454273

In containers, irqbalance likely can't do anything anyway.
In VMs, it might be redundant anyway as irqbalance is scheduling on virtual cpus (at least in some VMs)

Thoughts?

Implementation can be done simply in the systemd job by http://0pointer.de/blog/projects/detect-virt.html

**Comment by ppwaskie** [comment]
Restricting to not running in a container makes sense to me.  But VMs are a
bit trickier.  Especially when a VM can have a direct-assigned PCIe device,
or a VF assigned to a VM (via SR-IOV).

For the VM case, I'll need to mess around with some hardware that I have
buried in a pile in my office.  With an x2APIC and VF's or direct-assigned
devices, irqbalance in a VM makes sense to me, at the moment.  Let me do
some testing to confirm though.

**Comment by sikarash** [comment]
Even if a VM does not have either direct-assigned devices or VFs, running
irqbalance might be preferred depending on interrupt assignment to vCPUs
by the hypervisor. The case that a vCPU is exhausted to handle interrupts.

**Comment by nhorman** [comment]
This question has come up before and the consensus has generally been that while you typically wouldnt run irqbalance in virt/container environments, its not something we want to expressly prevent. as PJ notes, in virt environments VF's may need balancing, and thats actually true for containers as well (though not often used).  It generally doesn't do anything anyway in a virt environment anyway, so you just have to know to disable it if you don't need it.

**Comment by bigon** [comment]
@nhorman TBH, from a distribution POV, I would say it should be the other way around.

The distribution would pull irqbalance by default and it shouldn't run if not needed. If you really need it you should enabled it.

my 2¢

**Comment by bigon** [comment]
Mehhh, nevermind this is fixed already by a bug I opened myself...
