### ISSUE TITLE
irqbalance will cause nvme nvme0: I/O 1022 QID 22 timeout, Aborting, nvme nvme0: Abort status 0x0 ?

### ISSUE THREAD

**Issue by bigbang009** [Irqbalance/irqbalance#272]
VM environment：
CentOS Linux release 7.7.1908 (Core)
linux kernel: 4.19.95
irqbalance-1.0.7-12.el7.x86_64

Detail description：
when the irqbalance is enable and running, the nvme disk occured errors:

> 
nvme nvme0: I/O 1022 QID 22 timeout, Aborting,
nvme nvme0: Abort status 0x0
nvme nvme0: invalid id 0 completed on queue 14
> 
and the nvme msi not correct, 
![image](https://github.com/Irqbalance/irqbalance/assets/36918717/200c2a4c-c9cf-4b23-ac86-a7be20f1320a)

when i stop irqbalance and disable irqbalance the errors does not occure again, and the nvme msi is correct
![image](https://github.com/Irqbalance/irqbalance/assets/36918717/3208d7ae-36cb-45e6-9e66-f9e958f21188)

is there something wrong with the specified irqbalance? i do not knocw why.

**Comment by nhorman** [comment]
Call Red Hat.  irqbalance in Centos at version 1.0.7 is over 10 years old, and thats their build to support.  Your problem sounds vaguely like an irq pairing thing that might have been an issue on older nvme devices, but I might also be thinking of infiniband.  Either way, if you want me to look at it, first order of business would be to update irqbalance to the latest in the git tree
