### ISSUE TITLE
how do change loglevel in irqbalance?

### ISSUE THREAD

**Issue by tm4ig** [Irqbalance/irqbalance#283]
How Can I change loglevel in irqbalance?
irqbalance generates many annoying messages in systemd journal "Selecting irq ... for rebalancing".
I have tried set StandardOutput=null and StandardError=null in irqbalance systemd unit but this does not work fo me

**Comment by nhorman** [comment]
use the journaling option, and you can control the loglevel via the systemd/syslog configuration

**Comment by Maryse47** [comment]
> use the journaling option

@nhorman what do you mean? journaling is now [always enabled](https://github.com/Irqbalance/irqbalance/pull/278) when running on systemd service

I can set 
```
[Service]
LogLevelMax=5
```
to silence those locally (among other ones) but do you really think those countless `Selecting irq xxx for rebalancing` messages are useful for anyone on daily basis? Couldn't they be put behind  --debug` flag?

I think something is wrong when 90% journal messages comes from one service during its normal operation.

**Comment by nhorman** [comment]
Patches welcome
