### ISSUE TITLE
package vs numa node

### ISSUE THREAD

**Issue by holgerBerger** [Irqbalance/irqbalance#291]
when using 
 `balance_level=package`
it seems to balance on numa node, not package.
Is that intended?
Observed on a Xeon Scalable Processor gen4 (Sapphire Rapids) with SNC4 clustering,
where each socket has 4 NUMA nodes with irqbalance version 1.9.0
I would expect socket = package, not numa node = package.
I would like to have the actual socket, as the numa node is to small for the amount of interrupts,
but I can not see how I could do that.
Would it may be make sense to have `balance_level=[none | package | node | cache | core]` ?

**Comment by nhorman** [comment]
the balancing hierarchy was numa_node->package->cache->core

The selection for an appropriate numa node is handled in the do_one_cpu function, restricting the cpu selection to the intersection of the package mask and the node mask, so, yes, often balancing in your environment will lead to just balancing at the package level, which should be ok, given that we use a subset of cpus based on the intersection of the nearest node(s) and package(s)

You could I think achieve what you want by using the numa_node setting in your policy script to assign each cpu to a specific numa node.
