### ISSUE TITLE
Log spam in journald

### ISSUE THREAD

**Issue by cpaelzer** [Irqbalance/irqbalance#292]
Hi,
Ubuntu got this reported as a bug in [2046470](https://bugs.launchpad.net/ubuntu/+source/irqbalance/+bug/2046470).
A check of the history showed me that this happened

1. [back in the initial import this was a debug message](https://github.com/Irqbalance/irqbalance/commit/95f9881ff8d1032ae903bf700c17d6855bb1dacf#diff-74a30482d921ab3bffa86b0b1d5d481f70bff90c7ace5089813c521b98be07efR97)
2. [It got later converted to a log message and got INFO level (no more debug) but was unseen](https://github.com/Irqbalance/irqbalance/commit/c66ee249bdc356a39f81d389ec528730a1ab0451#diff-74a30482d921ab3bffa86b0b1d5d481f70bff90c7ace5089813c521b98be07efR321)
3. [it was moved around when introducing sockets, still unseen](https://github.com/Irqbalance/irqbalance/commit/d1993bcde2a524346a9508754671f096ec129ad1#diff-74a30482d921ab3bffa86b0b1d5d481f70bff90c7ace5089813c521b98be07efR255)
4. [recently not only foreground but also log_journal is auto-set](https://github.com/Irqbalance/irqbalance/commit/75a15c5dbe6b3a1fd50569b94359d22ae4116285)

Combined that leads to Ubuntu, Debian and probably all other users of the recent version with change number 4 to get continuous journal entries like this every 10 seconds:

```
Jan 05 12:30:55 n-vm irqbalance[770]: 
                                      
                                      
                                      -----------------------------------------------------------------------------
Jan 05 12:31:05 n-vm irqbalance[770]: 
                                      
                                      
                                      -----------------------------------------------------------------------------
Jan 05 12:31:15 n-vm irqbalance[770]: 
                                      
                                      
                                      -----------------------------------------------------------------------------
Jan 05 12:31:25 n-vm irqbalance[770]: 
                                      
                                      
                                      -----------------------------------------------------------------------------
Jan 05 12:31:35 n-vm irqbalance[770]: 
                                      
                                      
                                      -----------------------------------------------------------------------------
Jan 05 12:31:45 n-vm irqbalance[770]: 
                                      
                                      
                                      -----------------------------------------------------------------------------
```

It grabs a lot of space and it does not say what it is about.
That made sense back then when added as a message for the developer, but today is just annoying in the log.

I'd suggest to make this only shown in log level debug and to reduce the space it grabs as well as making it a bit more descriptive.

**Comment by paride** [comment]
Hi @cpaelzer, isn't this the same of of https://github.com/Irqbalance/irqbalance/issues/288, hopefully fixed by https://github.com/Irqbalance/irqbalance/commit/f3282f4ddc10be44e6c423de6de8db600f748f85 ?

**Comment by cpaelzer** [comment]
You are right, thanks for going through closed issues. It wasn't in the context of the bad line so I missed it. I'll give this a try and if good close this and the PR.

**Comment by cpaelzer** [comment]
Confirmed, better fixing twice than not at all :-)
But still closing this duplicate report - thanks
