### ISSUE TITLE
Access to /proc

### ISSUE THREAD

**Issue by RZR7332** [Irqbalance/irqbalance#296]
With reference to https://github.com/Irqbalance/irqbalance/issues/294 - is any sort of access to the /proc directory required other than the irqbalance directory? The below two options can also be enabled to further sandbox, essentially making other processes invisible to irqbalance:

✗ ProtectProc=                                                Service has full access to process tree (/proc hidepid=)                                                     0.2
✗ ProcSubset=                                                 Service has full access to non-process /proc files (/proc subset=)                                     0.1

Does irqbalance need to read anything else under /proc besides its own subdirectory?

**Comment by nhorman** [comment]
there is no such thing as the irqbalance directory in /proc.  I tihnk you are referring to the /proc/irq/* subtree?  yes, read/write access to that is required, as is /proc/interrupts/, /proc/stat, /proc/*/cmdline

I would not disable those settings
