### ISSUE TITLE
socket API blocks for 10s (sleep_interval)

### ISSUE THREAD

**Issue by champtar** [Irqbalance/irqbalance#298]
In `scan()`, we call `sleep_approx(sleep_interval)`, blocking the socket API (blocking the main_loop)
Looking at the code
https://github.com/Irqbalance/irqbalance/blob/64285577b465c4c5d8b5bbfa0120432e1d5ffd63/irqbalance.c#L320-L322
could we just replace those 3 lines with a return and still reenter `scan()` sleep_interval later (called by `g_timeout_add_seconds`)

**Comment by nhorman** [comment]
seems reasonable to me, can you submit a PR?
