### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by paulmenzel** [Irqbalance/irqbalance#31]
Version 1.1.0 was released over a year ago on December 4th, 2015. It’d be great, if you made a new release so that distributions, where most still track releases, can easily pick it up, and user can profit from the bug fixes and new features like a systemd service file.

**Comment by szepeviktor** [comment]
The changes: https://github.com/Irqbalance/irqbalance/compare/v1.1.0...master

**Comment by paulmenzel** [comment]
@szepeviktor, sorry for not checking it thoroughly. The systemd service unit [is already present in 1.1.0](https://github.com/Irqbalance/irqbalance/commits/master/misc/irqbalance.service).

I should have read the [Debian bug](https://bugs.debian.org/803232) report more carefully.

Still I think a new release would be beneficial.

**Comment by szepeviktor** [comment]
My comment was not meant to be snub you.

**Comment by paulmenzel** [comment]
@szepeviktor, I know. I just wanted to correct my statement. So thank you nevertheless.

**Comment by ppwaskie** [comment]
We'll work on it (meaning I need to coordinate with Neil and see who isn't
on vacation to pull the trigger on it).

So soon.

-PJ

**Comment by nhorman** [comment]
I made a new release on Jan 10
