### ISSUE TITLE
missing --hintpolicy option

### ISSUE THREAD

**Issue by freedomwarrior** [Irqbalance/irqbalance#311]
Hello.
I see that ```hintpolicy``` was removed.
What to do if I need to set ```numa_node=-1``` ?
Considering to this [problem](https://askubuntu.com/questions/852532/irqbalance-using-just-1-numa-nodes), we need also to set  ```hintpolicy``` for proper work of ```numa_node=-1```

**Comment by nhorman** [comment]
if you need to honor the affinity_hint exported by the kernel, guidance is to create a policy script, identifying those irqs that need to honor the hint, set ban=true and manually copy the affinity hint to the smp_affinity proc control for the irq

**Comment by liuchao173** [comment]
I don't think this [problem](https://askubuntu.com/questions/852532/irqbalance-using-just-1-numa-nodes) exists in the latest version.
irqbalance now behaves the same as when the "--hintpolicy=ignore" parameter is used. To solve this problem, you do not need to use hintpolicy.
If you want the smp_affinity and affinity_hint exported by the kernel to be the same, you can create a policy script.
