### ISSUE TITLE
Prevent irqbalance to start in containers

### ISSUE THREAD

**Issue by bigon** [Irqbalance/irqbalance#32]
Hi,

Ubuntu prevents irqbalance to start when installed in a container. Shouldn't this also be the case upstream?

This can be achieved by adding a `ConditionVirtualization=!container` in the `[Unit]` section of the .service file

**Comment by ppwaskie** [comment]
I think this should be conditional on the type of container and whether or
not a physical device is assigned to the container. I'd err on the side of
caution though and not start it by default.

-PJ

**Comment by nhorman** [comment]
fixed in commit d0405967a997c1e57d75541def45b5139677115b
