### ISSUE TITLE
A canonical path for policyscript

### ISSUE THREAD

**Issue by liutgnu** [Irqbalance/irqbalance#320]
Hi maintainers,

Do we have a canonical path for irqbalance's policyscript, or do you prefer to leave it to be designed by each distributions? I came to ask because users may place the policyscript file anywhere, with selinux enabled, it may prevent irqbalance from executing the policyscript file. Our selinux team is seeking for a preferred dir for the policyscript files (@zpytela please correct me if I'm wrong). I guess other distributions which enabled selinux may also encounter the same issue. Any ideas?

Thanks,
Tao Liu

**Comment by nhorman** [comment]
I think thats exactly why we need to leave this as a distribution decision.  A distributions should create their sysvinit/systemd unit such that they select a specific path for the policy script with the -l option, and setup their selinux policy to match it accordingly

**Comment by liutgnu** [comment]
OK, agreed. Thanks a lot for your explanation!
