### ISSUE TITLE
IRQBALANCE_ARGS should be explicitly defined to avoid systemd warning

### ISSUE THREAD

**Issue by Camelron** [Irqbalance/irqbalance#321]
Hello,

I noticed when updating systemd that some new noise was being produced by the systemd unit:

```
irqbalance: "Referenced but unset environment variable evaluates to an empty string: IRQBALANCE_ARGS"
```

It seems like systemd now logs when a variable expanded in a unit file is not explicitly defined. Thus, in the systemd service when we expand the variable this warning is logged https://github.com/Irqbalance/irqbalance/blob/master/misc/irqbalance.service#L11.  This behavior was introduced to systemd in versions 254+ https://github.com/systemd/systemd-stable/commit/f331434d13488425ccd8485327085d15f8f92aea 

I was able to squelch this warning by uncommenting IRQBALANCE_ARGS in irqbalance.env, instead setting it to the empty string. Might be worth handling upstream?

**Comment by nhorman** [comment]
yeah, that seems reasonable, if you would like to open a PR, I'd accept it.

Though that said, the systemd change seems somewhat...agressive.  lots of services have optional environment variables...
