### ISSUE TITLE
libcap-ng used by "/usr/sbin/irqbalance" failed due to not having CAP_SETPCAP in capng_apply

### ISSUE THREAD

**Issue by jpmv27** [Irqbalance/irqbalance#335]
Follow-up to https://github.com/Irqbalance/irqbalance/issues/182 and https://github.com/Irqbalance/irqbalance/pull/328.

This fix results in AVC errors from SELinux:
`SELinux is preventing /usr/sbin/irqbalance from setpcap access on the cap_userns labeled irqbalance_t`

Manually applying https://github.com/Irqbalance/irqbalance/commit/43751dfc7f29fbf2c46ffcd4fdb6d3f6db291927 and https://github.com/Irqbalance/irqbalance/commit/efab2725ea5165732c5e98c0e083a4eec6e355e3 also eliminates the message, but also results in the same SELinux AVC error.

I don't have enough expertise with SELinux to suggest a fix

**Comment by jpmv27** [comment]
```
time->Tue Dec  3 13:27:33 2024
type=PROCTITLE msg=audit(1733250453.504:3733): proctitle="/usr/sbin/irqbalance"
type=SYSCALL msg=audit(1733250453.504:3733): arch=c000003e syscall=157 success=yes exit=0 a0=18 a1=0 a2=0 a3=0 items=0 ppid=1 pid=94083 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="irqbalance" exe="/usr/sbin/irqbalance" subj=system_u:system_r:irqbalance_t:s0 key=(null)
type=AVC msg=audit(1733250453.504:3733): avc:  denied  { setpcap } for  pid=94083 comm="irqbalance" capability=8  scontext=system_u:system_r:irqbalance_t:s0 tcontext=system_u:system_r:irqbalance_t:s0 tclass=cap_userns permissive=1
```

**Comment by nhorman** [comment]
so, it looks like you built irqbalance with capng support, and selinux is telling you that, with your current selinux labeling, that the user running the binary doesn't have permissions to call setpcap from the libcap library.

You have two choices for fixing this:
1) Modify your selinux policy to allow it.  You can do this with the audit2allow command to generate a policy file that allows this operation, and then use semodule to insert the new policy into your systems policy database
or
2) Let another application handle capabilities for you.  You can build irqbalance without capng support, so the call will never be made

Given that your initial post referenced changes to the service file, I'm guessing you're using systemd, which can/will handle capabilities for you, and your selinux policy is likely set to already allow that.  My recommendation would be to follow path (2)

**Comment by jpmv27** [comment]
Thanks for the quick response.
I should've mentioned that this is on RHEL 9.5, I didn't personally build any of this.
It sounds like they need to apply your suggestion (2).

**Comment by jpmv27** [comment]
Those are changes to the systemd service file, so no rebuild was necessary, just systemctl edit.
