### ISSUE TITLE
External glib usage is manadatory due to recent commits

### ISSUE THREAD

**Issue by hnyman** [Irqbalance/irqbalance#40]
I have been trying to cross-compile irqbalance for Openwrt/LEDE and would like to avoid glib2 dependency. irqbalance provides a configure option for using the internal glib stub, but that option seems worthless after a recent commit that pollutes the main code with glib types without any attendance to the configure option.

commit https://github.com/Irqbalance/irqbalance/commit/d1993bcde2a524346a9508754671f096ec129ad1 uses glib types without any check for the configure option and makes having glib-unix.h mandatory in irqbalance.h: https://github.com/Irqbalance/irqbalance/commit/d1993bcde2a524346a9508754671f096ec129ad1#diff-a7a62c2ddfa68eb46761551bfbb16e84R11

It would be great if irqbalance could be compiled without external glib, as that is large dependency in embedded device context. I managed to do that by reverting the above commit, but should be unnecessary as there is configure switch for the glib usage.

EDIT:
Additionally, now that this commit is reverted, the "oneshot" parameter works again. 
With the original source code (with glib) I could not get irqbalance's oneshot mode to work, as it stayed running without quitting.

**Comment by hnyman** [comment]
cc also to @veruu who authored https://github.com/Irqbalance/irqbalance/commit/d1993bcde2a524346a9508754671f096ec129ad1

**Comment by nhorman** [comment]
I'm afraid we're likely not going to be able to keep up with the ability to avoid glib dependencies.  If you build statically the bits that we do use however should only amount to a few extra kb of space though

**Comment by hnyman** [comment]
Please then remove the configuration switch for glib usage. That is misleading if the intention is to depend on glib in any case.
https://github.com/Irqbalance/irqbalance/blob/master/configure.ac#L55

I guess that Openwrt/LEDE will then stick to the old version.
