### ISSUE TITLE
Add a configure switch for disabling UI component

### ISSUE THREAD

**Issue by hnyman** [Irqbalance/irqbalance#41]
In embedded device context the UI component may be unnecessary.
Please provide a configure switch to disable UI compilation.

(I disabled it manually by reverting https://github.com/Irqbalance/irqbalance/commit/bf9297132d219539e07506c125c6801dd77202f4 )

**Comment by veruu** [comment]
I'm away next week, but I'll take a look at both your issues as soon as I have time. Thanks for bringing it up!

**Comment by nhorman** [comment]
fixed in commit fd12d968a26b90117f71d0ddaee4532e770402d2

**Comment by szepeviktor** [comment]
https://github.com/Irqbalance/irqbalance/commit/fd12d968a26b90117f71d0ddaee4532e770402d2
