### ISSUE TITLE
Conflicting C89 and C99 Mode Requirement

### ISSUE THREAD

**Issue by rkubes** [Irqbalance/irqbalance#43]
A clean build of the master branch is failing on both the latest version of Raspbian on a Raspberry Pi, and Ubuntu 14.04 on a PC.

If left as-is, the build will fail on the UI code, with the following error:
```
ui/helpers.c: In function ‘hex_to_bitmap’:
ui/helpers.c:78:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
  for(int i = 3; i >= 0; i--) {
  ^
ui/helpers.c:78:2: note: use option -std=c99 or -std=gnu99 to compile your code
```
If this error is resolved manually, additional errors remain which also indicate the requirement C99 mode. All of these errors occur in the UI code. (*See edit below)

If the Makefile is modified to use -std=c99, the build will fail on the non-UI code with the following error:
```
numa.c:45:2: error: initializer element is not constant
  .mask = CPU_MASK_ALL,
  ^
numa.c:45:2: error: (near initialization for ‘unspecified_node_template.mask’)
```

The build will succeed if I build the UI portion on C99 mode, but the rest on C89 mode; but the Makefile does not seem to be configured to do this automatically.

Edit:
Upon further review, I realized all of the UI errors that indicate the requirement of C99 mode are the same. There are a number of 'for' loops with initial declarations. The build will be successful if all of the declarations are taken out of the 'for' loops.

The other remaining concerns are just warnings:
```
ui/irqbalance-ui.c: In function ‘main’:
ui/irqbalance-ui.c:378:6: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
      (void)fgets(cmdstring, 255, f);
      ^
ui/irqbalance-ui.c:403:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
```

**Comment by ppwaskie** [comment]
Closing as this builds fine with gcc 5.x and beyond.  Please upgrade your compilers.
