### ISSUE TITLE
1.2.0 Segmentation Fault

### ISSUE THREAD

**Issue by msmith626** [Irqbalance/irqbalance#46]
Hi,

I'm using irqbalance 1.2.0 and the daemon appears to run fine on it's own in the background, but after I launch irqbalance-ui, the irqbalance daemon dies with a segmentation fault. Below is a back-trace that I captured with GDB by using "irqbalance --debug" and then I ran irqbalance-ui and it crashed.

#0  0x00007ffff72177fa in __memmove_sse2_unaligned_erms () from /lib64/libc.so.6
#1  0x00007ffff72084ee in __GI__IO_default_xsputn () from /lib64/libc.so.6
#2  0x00007ffff71dccf7 in vfprintf () from /lib64/libc.so.6
#3  0x00007ffff71fd32b in vsprintf () from /lib64/libc.so.6
#4  0x00007ffff71e3767 in sprintf () from /lib64/libc.so.6
#5  0x0000000000405cfd in get_object_stat (object=0x61d450, data=0x7fffffffe030) at irqbalance.c:317
#6  0x0000000000405d3f in for_each_object (data=0x7fffffffe030, cb=0x405c80 <get_object_stat>, list=<optimized out>) at irqbalance.h:133
#7  get_object_stat (object=<optimized out>, data=0x7fffffffe030) at irqbalance.c:321
#8  0x0000000000405d3f in for_each_object (data=0x7fffffffe030, cb=0x405c80 <get_object_stat>, list=<optimized out>) at irqbalance.h:133
#9  get_object_stat (object=<optimized out>, data=0x7fffffffe030) at irqbalance.c:321
#10 0x0000000000405d3f in for_each_object (data=0x7fffffffe030, cb=0x405c80 <get_object_stat>, list=<optimized out>) at irqbalance.h:133
#11 get_object_stat (object=<optimized out>, data=0x7fffffffe030) at irqbalance.c:321
#12 0x000000000040603f in for_each_object (data=0x7fffffffe030, cb=0x405c80 <get_object_stat>, list=<optimized out>) at irqbalance.h:133
#13 sock_handle (fd=<optimized out>, condition=<optimized out>, user_data=<optimized out>) at irqbalance.c:364
#14 0x39205245424d554e in ?? ()
#15 0x20302044414f4c20 in ?? ()
#16 0x444f4d5f45564153 in ?? ()
#17 0x2051524920302045 in ?? ()
#18 0x44414f4c20323232 in ?? ()
#19 0x2046464944203020 in ?? ()
#20 0x205353414c432030 in ?? ()
#21 0x3332205152492034 in ?? ()
#22 0x302044414f4c2039 in ?? ()
#23 0x2030204646494420 in ?? ()
#24 0x2034205353414c43 in ?? ()
#25 0x2034333120515249 in ?? ()
#26 0x4420302044414f4c in ?? ()
#27 0x4c43203520464649 in ?? ()
#28 0x5249203420535341 in ?? ()
#29 0x4f4c203639312051 in ?? ()
#30 0x4649442030204441 in ?? ()
#31 0x53414c4320352046 in ?? ()
#32 0x2051524920342053 in ?? ()
#33 0x44414f4c20313033 in ?? ()
#34 0x2046464944203020 in ?? ()
#35 0x205353414c432030 in ?? ()
#36 0x3533205152492034 in ?? ()
...

Please let me know if there is any additional information I can provide.

--Marc

**Comment by nhorman** [comment]
yes, I can reproduce this here.  I'll look into it

**Comment by nhorman** [comment]
this is now fixed in commit 25e1af1b5f80eb33c62beea4274639e74b2ab828.  Thank you for the report
