### ISSUE TITLE
x86/x64: Devices with legacy IRQ 255 should be ignored

### ISSUE THREAD

**Issue by jslepicka** [Irqbalance/irqbalance#47]
Per the PCI Spec rev. 3.0, section 6.2.4: "For x86 based PCs, the values in [the Interrupt Line] register correspond to IRQ numbers (0-15) of the standard dual
8259 configuration. The value 255 is defined as meaning "unknown" or "no connection" to the interrupt
controller. Values between 15 and 254 are reserved."  Presumably, this applies to x64 systems as well.

This causes issues on machines that have both devices reporting legacy IRQ 255 and MSI IRQ 255:

IRQs 254 and 255 both belong to an Ethernet adapter:

```
# cat /proc/interrupts | egrep "25[45]:"
 254:...IR-PCI-MSI 68157441-edge      eth4-TxRx-1
 255:...IR-PCI-MSI 68157442-edge      eth4-TxRx-2
```

irqbalance correctly identifies IRQ 254, but thinks that 255 belongs to something else:

```
# /usr/sbin/irqbalance -d | egrep "25[4|5]"
Adding IRQ 255 to database
Adding IRQ 254 to database
  Interrupt 255 node_num is 0 (other/0:4)
  Interrupt 254 node_num is 1 (ethernet/0:4)
```

And assigns the wrong affinity mask to it (should be set to a single cpu):

```
# cat /proc/irq/255/smp_affinity
00000000,00000000,00000000,00000000,55555555,55555555
```

strace output reveals that irqbalance is finding a different device with legacy IRQ 255 and adding it to the database:

```
openat(AT_FDCWD, "/sys/bus/pci/devices/0000:00:16.0/msi_irqs", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/sys/bus/pci/devices/0000:00:16.0/irq", O_RDONLY) = 4
fstat(4, {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f5dc448b000
read(4, "255\n", 4096)                  = 4

# lspci | grep 00:16.0
00:16.0 Communication controller: Intel Corporation C610/X99 series chipset MEI Controller #1 (rev 05)
```

**Comment by ppwaskie** [comment]
On Wed, May 31, 2017 at 11:56 AM, jslepicka <notifications@github.com> wrote:
>
> Per the PCI Spec rev. 3.0, section 6.2.4: "For x86 based PCs, the values in [the Interrupt Line] register correspond to IRQ numbers (0-15) of the standard dual
> 8259 configuration. The value 255 is defined as meaning "unknown" or "no connection" to the interrupt
> controller. Values between 15 and 254 are reserved." Presumably, this applies to x64 systems as well.
>
> This causes issues on machines that have both devices reporting legacy IRQ 255 and MSI IRQ 255:
>
> IRQs 254 and 255 both belong to an Ethernet adapter:
>
> # cat /proc/interrupts | egrep "25[45]:"
>  254:...IR-PCI-MSI 68157441-edge      eth4-TxRx-1
>  255:...IR-PCI-MSI 68157442-edge      eth4-TxRx-2

These are both MSI interrupts though.  Legacy interrupts are marked
with IO-APIC.  So irqbalance is doing the right thing, unless I'm
missing something.

-PJ

**Comment by jslepicka** [comment]
They do show up correctly in /proc/interrupts, but when irqbalance scans /sys/bus/pci/devices to generate the database, it finds the device with legacy IRQ 255 and uses that instead.
