### ISSUE TITLE
Implementing irqbalance into the Linux Kernel

### ISSUE THREAD

**Issue by Sworddragon** [Irqbalance/irqbalance#59]
After using irqbalance now for several years I have questioned myself if irqbalance is still useful on a todays system (which seems to be true) and if yes why don't we have it as a kernel space solution directly implemented into the upstream kernel if it is that useful? It also makes me think if the Linux Kernel just lacks of IRQ balancing or if it is just not good enough and initially planned to create a feature request directly on the kernel tracker to implement such a solution but going here first might be the better choice.

So this ticket basically requests to polish irqbalance for the kernelspace and making a pull request to the upstream kernel. Or are there actually reasons why irqbalance should not directly be shipped with the kernel / upstream should not develop such a solution?

**Comment by ppwaskie** [comment]
Are you asking to merge irqbalance into the kernel itself?  This has been
discussed before at length.  What sort of reasons do you have to merge it
into the kernel?

The reasoning why it isn't part of the kernel is the kernel provides the
facilities to enforce policy, but the kernel itself does not decide on
policy.  Rather, userspace should make use of all the information available
to it exported from the kernel to then decide on and enforce a system-wide
policy.  The kernel may not have pieces that are able to take the entire
system into account when making balancing decisions.  Userspace typically
has the broader view of the world when making those decisions.

-PJ

**Comment by Sworddragon** [comment]
> Are you asking to merge irqbalance into the kernel itself?

Yes.


> What sort of reasons do you have to merge it into the kernel?

Microoptimizations (for example it would be nice to have the process list as less bloated as possible), concept issues (such generic optimizations look to me that they should actually be in the kernel - this way users can also take advantage more easily of these optimizations if they are directly shipped with the kernel - avoiding the use to research for all possible optimization tools (irqbalance, numad, etc.); it could avoid specific userspace issues - for example lately on Ubuntu with systemd irqbalance needs some additional seconds than usual to shutdown causing the system shutdown to be delayed (but I'm going to report it directly to Ubuntu)). Nothing that special as you see - but things nice to have.


> The reasoning why it isn't part of the kernel is the kernel provides the facilities to enforce policy, but the kernel itself does not decide on policy.

CPU modules also have the capability to enforce different policies. For example a policy by providing the maximum performance and automatic ones by setting dynamically the CPU frequencies based on the load. We could also have this for IRQ balancing for example by having a static policy and a dynamic policy.

**Comment by ppwaskie** [comment]
On Tue, Oct 31, 2017 at 8:54 PM, Sworddragon <notifications@github.com> wrote:
>
> Are you asking to merge irqbalance into the kernel itself?
>
> Yes.
>
> What sort of reasons do you have to merge it into the kernel?
>
> Microoptimizations (for example it would be nice to have the process list as less bloated as possible), concept issues (such generic optimizations look to me that they should actually be in the kernel - this way users can also take advantage more easily of these optimizations if they are directly shipped with the kernel - avoiding the use to research for all possible optimization tools (irqbalance, numad, etc.); it could avoid specific userspace issues - for example lately on Ubuntu with systemd irqbalance needs some additional seconds than usual to shutdown causing the system shutdown to be delayed (but I'm going to report it directly to Ubuntu)). Nothing that special as you see - but things nice to have.

It's not just about the process lists.  The policy enforcer needs to
also understand the system topology (NUMA, non-NUMA), all of the
connected devices requesting interrupts (PCIe root complex, PCIe
bridges, etc.), and then decide how best to service the system as a
whole.  While the kernel could have something that does this (the IRQ
balancer originally was in-kernel), it's more appropriate for that
level of oversight be performed by userspace.

And the comment regarding concept issues, this is again akin to what
the kernel attempts to provide.  The kernel provides the mechanisms to
implement a policy, and userspace implements the policy.

>
> The reasoning why it isn't part of the kernel is the kernel provides the facilities to enforce policy, but the kernel itself does not decide on policy.
>
> CPU modules also have the capability to enforce different policies. For example a policy by providing the maximum performance and automatic ones by setting dynamically the CPU frequencies based on the load. We could also have this for IRQ balancing for example by having a static policy and a dynamic policy.

Not exactly.  Which CPU governor is enabled is provided by userspace.
There is a "default" based on how the kernel was built, but if one
wanted performance versus power savings, that is a sysfs interface
that userspace interacts with to change it.  Also, userspace is used
to offline CPUs, online them, etc.

Device drivers, who are the biggest direct user of multiple
interrupts, currently have a mechanism to request a suggested CPU
affinity map for IRQ affinity.  That is exposed in
/proc/irq/<irqnum>/affinity_hint.  irqbalance uses that to then apply
it to /proc/irq/<irqnum>/smp_affinity, which is then applied to the
actual APIC tables in the kernel/hardware.

I guess I'm not seeing a compelling reason or issue you're running
into that would warrant such a change, aside from it just making sense
in your opinion.  The systemd issue with irqbalance taking a long time
to shut down in Ubuntu is completely orthogonal to this discussion
though, as that's a system management problem with their unit files.

-PJ

**Comment by nhorman** [comment]
Completely agree with @ppwaskie .  The idea of moving irqbalance into the kernel has been hashed over,and there is simply no good reason to do so.  irqbalance is responsible for the creation and communication of irq affinity policy to the kernel, and as such is firmly in the domain of user space.  Its certainly possible for us to do so, just not desired.  I'm sorry, but this isn't a bug.

That said, your mention of delayed shutdown is troubling.  as PJ notes, it likely is a problem with how the  distribution is halting the process.  Depending on your ubuntu release, it may still be using sysv init scrits (which is fine, but they use start-stop-daemon, which can have its own latency that needs to be addressed).  I would suggest opening a bug with ubuntu on that subject, and having them look into it.  If they find an issue with how irqbalance receives shutdown signals, then you or they can open a new bz here.
