### ISSUE TITLE
Issue in 1.2.0 Package, New release possible

### ISSUE THREAD

**Issue by vlsireddy** [Irqbalance/irqbalance#60]
Hi,
   I see in the 1.2.0 release [tar and other zipped files] [released on Jan 10] has this bug.
commit : - b0f77c10fc4561463b59b12cba0bfd69d7c73934

https://github.com/Irqbalance/irqbalance/commit/b0f77c10fc4561463b59b12cba0bfd69d7c73934#diff-69b8dbcfbbf11746aa38c26a4604e551

Do you plan to put up a new release of release compressed files?

Thanks

**Comment by nhorman** [comment]
If you want to issue a pull request against this issue, I'll gladly pull in the fix, but we're not going to re-release the package just for what will otherwise be a compiler warning.

**Comment by vlsireddy** [comment]
Hi Neil,
        Thanks for reply. 
The issue is fixed after 1.2.0 release [tar.xz] . 
For AARCH64 compilation, it is not a compiler warning, its a compiler **Error**.
so let me know your re-take on the issue.

Thanks

**Comment by nhorman** [comment]
Oh, I see what you're saying.  I hadn't really planned to do another release for just that fix, but we have ammased several other fixes that could go into a release here.  I'll put it together today
