### ISSUE TITLE
Prints warning for CPU hotplug operation which can confuse to users. 

### ISSUE THREAD

**Issue by hmyneni** [Irqbalance/irqbalance#62]
For each CPU hotpug operation, the following warning is logged in /var/log/messages which can add confusion to users.

WARNING, didn't collect load info for all cpus, balancing is broken

parse_proc_stat() is called again during CPU hotplug detection (need_rescan) after rebuilding CPU tree. So no need to call this function twice. So execute parse_proc_stat() after clear/rebuild CPU tree during CPU hotplug detection.

**Comment by hmyneni** [comment]
Fix is available in https://github.com/hmyneni/irqbalance.git (branch:dev 3678e0b579d82cc4d560f7c0718d531914322586)

**Comment by nhorman** [comment]
accepted.  Made one small semantic change to allow for the elimination of that else clause.  

Please note, that you seems to have created your irqbalance repo independently.  If in the future you fork it from this repo instead, you will more easily be able to create pull requests

**Comment by hmyneni** [comment]
Thanks,
