### ISSUE TITLE
AMD G-T40E Processor (http ://pcengines.ch/apu1d4.htm hardware)

### ISSUE THREAD

**Issue by painfull30** [Irqbalance/irqbalance#71]
Hi! Thanks for a work ) Not work best on devices like http://pcengines.ch/apu1d4.htm

`root@50008:~# cat /proc/interrupts
           CPU0       CPU1
  0:         53          0   IO-APIC   2-edge      timer
  4:          0   38321238   IO-APIC   4-edge      serial
  8:          0          1   IO-APIC   8-edge      rtc0
  9:          0          0   IO-APIC   9-fasteoi   acpi
 17:          4    7577557   IO-APIC  17-fasteoi   ehci_hcd:usb1, ehci_hcd:usb2, ehci_hcd:usb3
 18:          0          0   IO-APIC  18-fasteoi   ohci_hcd:usb4, ohci_hcd:usb5, ohci_hcd:usb6, ohci_hcd:usb7
 19:         12   22497465   IO-APIC  19-fasteoi   ahci[0000:00:11.0]
 24:          0          0   PCI-MSI 65536-edge      PCIe PME
 25:          0          0   PCI-MSI 81920-edge      PCIe PME
 26:          0          0   PCI-MSI 98304-edge      PCIe PME
 27:          0          0   PCI-MSI 344064-edge      PCIe PME
 28:          0 1379468797   PCI-MSI 524288-edge      eth0
 29:          0 2267923434   PCI-MSI 1048576-edge      eth1
 30:          0    3481603   PCI-MSI 1572864-edge      eth2
NMI:      54018      83239   Non-maskable interrupts
LOC:  372723857 1228258574   Local timer interrupts
SPU:          0          0   Spurious interrupts
PMI:      54018      83239   Performance monitoring interrupts
IWI:  127027444  127299591   IRQ work interrupts
RTR:          0          0   APIC ICR read retries
RES:  276767033  193796509   Rescheduling interrupts
CAL:    1760759    1821924   Function call interrupts
TLB:    1667617    1706879   TLB shootdowns
TRM:          0          0   Thermal event interrupts
THR:          0          0   Threshold APIC interrupts
DFR:          0          0   Deferred Error APIC interrupts
MCE:          0          0   Machine check exceptions
MCP:       5453       5453   Machine check polls
ERR:          1
MIS:          0
PIN:          0          0   Posted-interrupt notification event
PIW:          0          0   Posted-interrupt wakeup event`
===================================================================
root@50008:~# irqbalance -d
Isolated CPUs: 00000001
Adaptive-ticks CPUs: 00000000
Package 0:  numa_node is 0 cpu mask is 00000002 (load 0)
        Cache domain 0:  numa_node is 0 cpu mask is 00000002  (load 0)
                CPU number 1  numa_node is 0 (load 0)
Adding IRQ 17 to database
Adding IRQ 18 to database
Adding IRQ 27 to database
Adding IRQ 26 to database
Adding IRQ 19 to database
Adding IRQ 25 to database
Adding IRQ 30 to database
Adding IRQ 29 to database
Adding IRQ 24 to database
Adding IRQ 28 to database
Adding IRQ 0 to database
Adding IRQ 4 to database
Adding IRQ 8 to database
Adding IRQ 9 to database
NUMA NODE NUMBER: -1
LOCAL CPU MASK: ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff

NUMA NODE NUMBER: 0
LOCAL CPU MASK: 00000003

-----------------------------------------------------------------------------
Package 0:  numa_node is 0 cpu mask is 00000002 (load 0)
        Cache domain 0:  numa_node is 0 cpu mask is 00000002  (load 0)
                CPU number 1  numa_node is 0 (load 0)
                  Interrupt 28 node_num is -1 (ethernet/0:3558)
                  Interrupt 29 node_num is -1 (ethernet/0:7754)
                  Interrupt 30 node_num is -1 (ethernet/0:4)
                  Interrupt 19 node_num is -1 (storage/0:104)
          Interrupt 24 node_num is -1 (legacy/0:0)
          Interrupt 25 node_num is -1 (legacy/0:0)
          Interrupt 18 node_num is -1 (legacy/0:0)
          Interrupt 26 node_num is -1 (legacy/0:0)
          Interrupt 27 node_num is -1 (legacy/0:0)
          Interrupt 17 node_num is -1 (legacy/0:36)
  Interrupt 9 node_num is -1 (other/0:0)
  Interrupt 8 node_num is -1 (other/0:0)
  Interrupt 4 node_num is -1 (other/0:276)
  Interrupt 0 node_num is -1 (other/0:0)

-----------------------------------------------------------------------------
Package 0:  numa_node is 0 cpu mask is 00000002 (load 320000000)
        Cache domain 0:  numa_node is 0 cpu mask is 00000002  (load 320000000)
                CPU number 1  numa_node is 0 (load 320000000)
                  Interrupt 28 node_num is -1 (ethernet/109974690:3178)
                  Interrupt 29 node_num is -1 (ethernet/198528885:5737)
                  Interrupt 30 node_num is -1 (ethernet/484470:14)
                  Interrupt 19 node_num is -1 (storage/1937880:56)
          Interrupt 24 node_num is -1 (legacy/1:0)
          Interrupt 25 node_num is -1 (legacy/1:0)
          Interrupt 18 node_num is -1 (legacy/1:0)
          Interrupt 26 node_num is -1 (legacy/1:0)
          Interrupt 27 node_num is -1 (legacy/1:0)
          Interrupt 17 node_num is -1 (legacy/1557225:45)
  Interrupt 9 node_num is -1 (other/1:0)
  Interrupt 8 node_num is -1 (other/1:0)
  Interrupt 4 node_num is -1 (other/7509285:217)
  Interrupt 0 node_num is -1 (other/1:0)

-----------------------------------------------------------------------------
Package 0:  numa_node is 0 cpu mask is 00000002 (load 630000000)
        Cache domain 0:  numa_node is 0 cpu mask is 00000002  (load 630000000)
                CPU number 1  numa_node is 0 (load 630000000)
                  Interrupt 28 node_num is -1 (ethernet/182556010:2905)
                  Interrupt 29 node_num is -1 (ethernet/412369204:6562)
                  Interrupt 30 node_num is -1 (ethernet/2073786:33)
                  Interrupt 19 node_num is -1 (storage/18035654:287)
          Interrupt 24 node_num is -1 (legacy/1:0)
          Interrupt 25 node_num is -1 (legacy/1:0)
          Interrupt 18 node_num is -1 (legacy/1:0)
          Interrupt 26 node_num is -1 (legacy/1:0)
          Interrupt 27 node_num is -1 (legacy/1:0)
          Interrupt 17 node_num is -1 (legacy/2827890:45)
  Interrupt 9 node_num is -1 (other/1:0)
  Interrupt 8 node_num is -1 (other/1:0)
  Interrupt 4 node_num is -1 (other/12128506:193)
  Interrupt 0 node_num is -1 (other/1:0)

-----------------------------------------------------------------------------
Package 0:  numa_node is 0 cpu mask is 00000002 (load 450000000)
        Cache domain 0:  numa_node is 0 cpu mask is 00000002  (load 450000000)
                CPU number 1  numa_node is 0 (load 450000000)
                  Interrupt 28 node_num is -1 (ethernet/140649912:2808)
                  Interrupt 29 node_num is -1 (ethernet/289564509:5781)
                  Interrupt 30 node_num is -1 (ethernet/1552759:31)
                  Interrupt 19 node_num is -1 (storage/3856853:77)
          Interrupt 24 node_num is -1 (legacy/1:0)
          Interrupt 25 node_num is -1 (legacy/1:0)
          Interrupt 18 node_num is -1 (legacy/1:0)
          Interrupt 26 node_num is -1 (legacy/1:0)
          Interrupt 27 node_num is -1 (legacy/1:0)
          Interrupt 17 node_num is -1 (legacy/2254005:45)
  Interrupt 9 node_num is -1 (other/1:0)
  Interrupt 8 node_num is -1 (other/1:0)
  Interrupt 4 node_num is -1 (other/12121538:242)
  Interrupt 0 node_num is -1 (other/1:0)

-----------------------------------------------------------------------------
Package 0:  numa_node is 0 cpu mask is 00000002 (load 360000000)
        Cache domain 0:  numa_node is 0 cpu mask is 00000002  (load 360000000)
                CPU number 1  numa_node is 0 (load 360000000)
                  Interrupt 28 node_num is -1 (ethernet/117364158:2822)
                  Interrupt 29 node_num is -1 (ethernet/227034351:5459)
                  Interrupt 30 node_num is -1 (ethernet/540657:13)
                  Interrupt 19 node_num is -1 (storage/4782735:115)
          Interrupt 24 node_num is -1 (legacy/1:0)
          Interrupt 25 node_num is -1 (legacy/1:0)
          Interrupt 18 node_num is -1 (legacy/1:0)
          Interrupt 26 node_num is -1 (legacy/1:0)
          Interrupt 27 node_num is -1 (legacy/1:0)
          Interrupt 17 node_num is -1 (legacy/1871505:45)
  Interrupt 9 node_num is -1 (other/1:0)
  Interrupt 8 node_num is -1 (other/1:0)
  Interrupt 4 node_num is -1 (other/8400978:202)
  Interrupt 0 node_num is -1 (other/1:0)

-----------------------------------------------------------------------------
Package 0:  numa_node is 0 cpu mask is 00000002 (load 380000000)
        Cache domain 0:  numa_node is 0 cpu mask is 00000002  (load 380000000)
                CPU number 1  numa_node is 0 (load 380000000)
                  Interrupt 28 node_num is -1 (ethernet/99876276:2196)
                  Interrupt 29 node_num is -1 (ethernet/262197965:5765)
                  Interrupt 30 node_num is -1 (ethernet/500291:11)
                  Interrupt 19 node_num is -1 (storage/4184252:92)
          Interrupt 24 node_num is -1 (legacy/1:0)
          Interrupt 25 node_num is -1 (legacy/1:0)
          Interrupt 18 node_num is -1 (legacy/1:0)
          Interrupt 26 node_num is -1 (legacy/1:0)
          Interrupt 27 node_num is -1 (legacy/1:0)
          Interrupt 17 node_num is -1 (legacy/2046645:45)
  Interrupt 9 node_num is -1 (other/1:0)
  Interrupt 8 node_num is -1 (other/1:0)
  Interrupt 4 node_num is -1 (other/11188326:246)
  Interrupt 0 node_num is -1 (other/1:0)
^C

-----------------------------------------------------------------------------
Package 0:  numa_node is 0 cpu mask is 00000002 (load 70000000)
        Cache domain 0:  numa_node is 0 cpu mask is 00000002  (load 70000000)
                CPU number 1  numa_node is 0 (load 70000000)
                  Interrupt 28 node_num is -1 (ethernet/17331790:490)
                  Interrupt 29 node_num is -1 (ethernet/49094948:1388)
                  Interrupt 30 node_num is -1 (ethernet/353710:10)
                  Interrupt 19 node_num is -1 (storage/459823:13)
          Interrupt 24 node_num is -1 (legacy/1:0)
          Interrupt 25 node_num is -1 (legacy/1:0)
          Interrupt 18 node_num is -1 (legacy/1:0)
          Interrupt 26 node_num is -1 (legacy/1:0)
          Interrupt 27 node_num is -1 (legacy/1:0)
          Interrupt 17 node_num is -1 (legacy/318339:9)
  Interrupt 9 node_num is -1 (other/1:0)
  Interrupt 8 node_num is -1 (other/1:0)
  Interrupt 4 node_num is -1 (other/2440599:69)
  Interrupt 0 node_num is -1 (other/1:0)
===================================================================
root@50008:~#  for i in $(seq 0 300); do grep . /proc/irq/$i/smp_affinity /dev/null 2>/dev/null; done
/proc/irq/0/smp_affinity:3
/proc/irq/1/smp_affinity:3
/proc/irq/2/smp_affinity:3
/proc/irq/3/smp_affinity:3
/proc/irq/4/smp_affinity:2
/proc/irq/5/smp_affinity:3
/proc/irq/6/smp_affinity:3
/proc/irq/7/smp_affinity:3
/proc/irq/8/smp_affinity:2
/proc/irq/9/smp_affinity:2
/proc/irq/10/smp_affinity:3
/proc/irq/11/smp_affinity:3
/proc/irq/12/smp_affinity:3
/proc/irq/13/smp_affinity:3
/proc/irq/14/smp_affinity:3
/proc/irq/15/smp_affinity:3
/proc/irq/17/smp_affinity:2
/proc/irq/18/smp_affinity:2
/proc/irq/19/smp_affinity:2
/proc/irq/24/smp_affinity:2
/proc/irq/25/smp_affinity:2
/proc/irq/26/smp_affinity:2
/proc/irq/27/smp_affinity:2
/proc/irq/28/smp_affinity:2
/proc/irq/29/smp_affinity:2
/proc/irq/30/smp_affinity:2
===================================================================
root@50008:~# lstopo-no-graphics
Machine (3925MB)
  Package L#0
    L2 L#0 (512KB) + L1d L#0 (32KB) + L1i L#0 (32KB) + Core L#0 + PU L#0 (P#0)
    L2 L#1 (512KB) + L1d L#1 (32KB) + L1i L#1 (32KB) + Core L#1 + PU L#1 (P#1)
  HostBridge L#0
    PCIBridge
      PCI 10ec:8168
        Net L#0 "eth0"
    PCIBridge
      PCI 10ec:8168
        Net L#1 "eth1"
    PCIBridge
      PCI 10ec:8168
        Net L#2 "eth2"
    PCI 1002:4391
      Block(Disk) L#3 "sda"
==================================================
I tested manually, if assign diff cores manually to first and 2nd ethernets - " traffic passthrough" of device device x1.5 higher

**Comment by nhorman** [comment]
It looks like the systems ACPI tables aren't built correctly.  The debug output shows that the one numa node on the system (numa node 0) has a cpu affinity mask of 0x2, meaning irqbalance will think that there is only one cpu on the system (cpu id 1), and so is assigning all interrupts there.  You need to contact the board manufacturer to issue a firmware update that properly ennumerates all the cpus into a numa node.

**Comment by painfull30** [comment]
Thanks, sent to manufacturer. Must be there no way to manually force to irqbalance number of cores in some config or param, yet?

**Comment by nhorman** [comment]
you can use the policyscript option.  Basically just write a script that:
1) selects a core in a round robin fashion among the cores you know are available and assigns that value by exeucting echo $CORE > /proc/irq/$IRQ/smp_affinity (replacing IRQ with the parameter from the man page)
and
2) echos ban=true to the standard output to prevent irqbalance from overriding it
