### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by GasGeverij** [Irqbalance/irqbalance#73]
I'm on Ubuntu 16.04 and config and autogen works now but i get this error when making 

In file included from ui/helpers.c:7:0:
ui/ui.h:7:20: fatal error: curses.h: No such file or directory
compilation terminated.
Makefile:581: recipe for target 'ui/helpers.o' failed
make[2]: *** [ui/helpers.o] Error 1
make[2]: Leaving directory '/root/irqbalance'
Makefile:648: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/irqbalance'
Makefile:457: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ppwaskie** [comment]
Looks like you're missing the ncurses development package.

# apt-get install libncurses-dev

And then try again.

**Comment by nhorman** [comment]
I agree this looks pretty straightfoward, please re-open if that doesn't solve the problem.
