### ISSUE TITLE
ksoftirqd kworker locked up at 100% after small packet bursts duplicate

### ISSUE THREAD

**Issue by AlexProfi** [Irqbalance/irqbalance#94]
I see previous issue and there is no answer
I get similar problem I get 12 ksoftirqd processes each of them eats 100% cpu

Detail of my config
1) kubernetes cluster 1.11.5
2) daemonset with nginx that transfer data to backends ( wcf services) through proxy_pass
3) HP BL 460 Gen 9
4) I don't find any irqbalance config in my system please write where I can find it
5)  for i in {85..94}; do echo -n "Interrupt $i is allowed on CPUs "; cat /proc/irq/$i/smp_affinity_list; done
Interrupt 85 is allowed on CPUs 19
Interrupt 86 is allowed on CPUs cat: /proc/irq/86/smp_affinity_list: No such file or directory
Interrupt 87 is allowed on CPUs 6
Interrupt 88 is allowed on CPUs 5
Interrupt 89 is allowed on CPUs 4
Interrupt 90 is allowed on CPUs 3
Interrupt 91 is allowed on CPUs 2
Interrupt 92 is allowed on CPUs 1
Interrupt 93 is allowed on CPUs 16
Interrupt 94 is allowed on CPUs 23
6) /proc/interrupts:  85:         55        100         10        705       1346       1150        302       7206          0          0          0          0          0          0          0          0        816        111        201       1226         29         10         11       1730          0          0          0          0          0          0          0          0  IR-PCI-MSI 3145728-edge      eno49
/proc/interrupts:  87:         41          0          0          0          0          0   31636884          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0  IR-PCI-MSI 3145730-edge      eno49-fp-0
/proc/interrupts:  88:         20          0          0          0          0    5009704          0          0          0          0          0          0          0          0          0          0          0          0          0          0   26673651          0          0          0          0          0          0          0          0          0          0          0  IR-PCI-MSI 3145731-edge      eno49-fp-1
/proc/interrupts:  89:         15   25641448          0          0    6565070          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0  IR-PCI-MSI 3145732-edge      eno49-fp-2
/proc/interrupts:  90:         24          0          0    5004966          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0   26598609          0          0          0          0          0          0          0          0          0  IR-PCI-MSI 3145733-edge      eno49-fp-3
/proc/interrupts:  91:         29          0   32362176          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0  IR-PCI-MSI 3145734-edge      eno49-fp-4
/proc/interrupts:  92:         15    4956725          0          0          0   28059937          0          0          0          0          0          0          0          0          0          0        299          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0  IR-PCI-MSI 3145735-edge      eno49-fp-5
/proc/interrupts:  93:        231          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0   31928948          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0  IR-PCI-MSI 3145736-edge      eno49-fp-6
/proc/interrupts:  94:        242      12286          0          0   24899048          0         74          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0    6541877          0          0          0          0          0          0          0          0  IR-PCI-MSI 3145737-edge      eno49-fp-7
If it is not enough please write what I need else?

**Comment by nhorman** [comment]
ksoftirqd is the kernel irq handling daemon for softirqs, and has nothing to do with irqbalance.  A lockup in ksoftirqd typically indicates that you have a driver which has an incorrectly written softirq handling routine.  I suggest you run sysrq-t when the lockup happens, and report your findings to the kernel community, or your distribution vendor.

by default irqbalance has no configuration, but if you read the man page you can see the command line options available
