### ISSUE TITLE
1.6.0: test suite is failing

### ISSUE THREAD

**Issue by kloczek** [Irqbalance/irqbalance#97]
<pre>+ /usr/bin/make -O -j4 check
Making check in tests
/usr/bin/make  runoneshot.sh 
make[2]: Nothing to be done for &apos;runoneshot.sh&apos;.
/usr/bin/make  check-TESTS
make[3]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/irqbalance-1.6.0/tests&apos;
FAIL: runoneshot.sh
make[3]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/irqbalance-1.6.0/tests&apos;
make[3]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/irqbalance-1.6.0/tests&apos;
============================================================================
Testsuite summary for irqbalance 1.6.0
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See tests/test-suite.log
============================================================================
</pre>
[test-suite.log](https://github.com/Irqbalance/irqbalance/files/3211004/test-suite.log)

**Comment by nhorman** [comment]
try running make check as root?

**Comment by kloczek** [comment]
Issue is that I'm trying to use every possible package included test suites during package build and all my packages are build from non-root.
I've not been looking enough close on test suite. For what is needed root per in Irqbalance test suite?

**Comment by nhorman** [comment]
The creation of a unix socket on a path that only has write permission for
root

**Comment by kloczek** [comment]
FYi rpm is using https://github.com/dex4er/fakechroot/ to perform in similar context  some tests in test suite.
https://github.com/rpm-software-management/rpm/tree/master/tests

**Comment by nhorman** [comment]
Not sure what to tell you there.  I just tried this using the fakeroot package on fedora, and it works fine.    It sounds to me like something in your environment is preventing irqbalance from creating unix sockets.  If you can't try running as root, then I suggest you run the built binary in your test environment under a debugger, and see what the return code from the bind calls are.  That should point you more specifically toward what the problem you are encountering is

**Comment by kloczek** [comment]
Will try to check this one more time tomorrow :)

**Comment by nhorman** [comment]
ping?

**Comment by kloczek** [comment]
Sorry I'm busy now. Will back to you at the end of the week.

kloczek
-- 
Tomasz Kłoczko | LinkedIn: *http://lnkd.in/FXPWxH <http://lnkd.in/FXPWxH>*

**Comment by nhorman** [comment]
ping, any update here?  If you don't have time to work on this, i'll close it, and you can reopen it when you do
