### ISSUE TITLE
Issue with 1.0.4 - 8sg system not balancing all IRQs

### ISSUE THREAD

**Issue by Pitterling** [Irqbalance/irqbalance#99]
SLES11.4 is shipped with old irqbalance version 1.0.4

This is a 8 Socket server with Intel Ethernet and LSI MegaSAS devices.
IRQ on this system mostly end up on CPU0 and CPU1.

NUMA node0 CPU(s):     0-14,120-134
NUMA node1 CPU(s):     15-29,135-149
NUMA node2 CPU(s):     30-44,150-164
NUMA node3 CPU(s):     45-59,165-179
NUMA node4 CPU(s):     60-74,180-194
NUMA node5 CPU(s):     75-89,195-209
NUMA node6 CPU(s):     90-104,210-224
NUMA node7 CPU(s):     105-119,225-239

Each device has multiple queues, e.g. eth0-TxRx-[0-63] or  megasas 32.

The first 15 interrupts of each device are well distributed across the cores of the belonging numa node. The mess starts with the 16th interrupt and higher of each device.
While the smp_affinity is correctly set for the first interrupts, the smp_affinity for IRQ16th is set to all CPUs. Also the affinity_hint is not correct (CPU from wrong NUMA node) 

here is an example:
eth0-TxRx-14	IRQ 161 = ok		00004000 = CPU14 = NUMA0
eth0-TxRx-15	IRQ 162 = NOT ok	00008000 = CPU15 = NUMA1

/proc/irq/161/node:0
/proc/irq/161/smp_affinity_list:14
/proc/irq/161/affinity_hint:00000000,00000000,00000000,00000000,00000000,00000000,00000000,00004000
/proc/irq/161/smp_affinity:00000000,00000000,00000000,00000000,00000000,00000000,00000000,00004000

/proc/irq/162/node:0
/proc/irq/162/smp_affinity_list:0-239
/proc/irq/162/affinity_hint:00000000,00000000,00000000,00000000,00000000,00000000,00000000,00008000
/proc/irq/162/smp_affinity:0000ffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff

I attached the debug output and a strace ..

[interrupts.txt](https://github.com/Irqbalance/irqbalance/files/3263602/interrupts.txt)
[irq_affinity.txt](https://github.com/Irqbalance/irqbalance/files/3263603/irq_affinity.txt)
[irqbalance_debug.txt](https://github.com/Irqbalance/irqbalance/files/3263604/irqbalance_debug.txt)
[irqbalance_info.txt](https://github.com/Irqbalance/irqbalance/files/3263605/irqbalance_info.txt)
[irqbalance_trace.txt](https://github.com/Irqbalance/irqbalance/files/3263607/irqbalance_trace.txt)

Any advise would be highly appreciated.

**Comment by nhorman** [comment]
First step is build the head of the irqbalance tree and see if you can
reproduce the problem.  1.0.4 is so old there's no point in looking at
anything before you update it.

Neil

**Comment by Pitterling** [comment]
Thank you Neil.

How do I build the head of the tree?
I know this version is ancient, but this is the official shipped SUSE version.

Peter

**Comment by nhorman** [comment]
If you don't know how to build the code, then this really isn't the right
forum for you.   You're going to need to be able to build and make changes
to the code to fully debug any issue I can help you with. It sounds like
you need to open a support case with suse.

Neil

**Comment by Pitterling** [comment]
Ah .. i misunderstood .. I thought i should reset the irqbalancer state, but you were just referring to the latest greatest code ..

**Comment by nhorman** [comment]
Yes, can you do that?

**Comment by Pitterling** [comment]
I will try. This is a customer prod system and i don't have direct access ... I 'll update this issue when i get more information.

**Comment by nhorman** [comment]
If this is a production system and a Suse Enterprise product, why are yo not opening up a support case with Suse?

**Comment by Pitterling** [comment]
already tried several times, no valuable outcome.

**Comment by nhorman** [comment]
That seems...wrong.  If they are supporting an old version, they need to support it.  I can help you, if you can reproduce this on the latest version, but eventually you will need to get Suse to engage on this issue, unless you are thinking about changing distributions

**Comment by Pitterling** [comment]
I know its wrong .. 

currently make is failing ... glib-unix.h is missing
```console
 # make
make  all-recursive
make[1]: Entering directory `/root/pp/irqbalance'
Making all in tests
make[2]: Entering directory `/root/pp/irqbalance/tests'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/root/pp/irqbalance/tests'
make[2]: Entering directory `/root/pp/irqbalance'
gcc -DHAVE_CONFIG_H -I.  -I. -W -Wall -Wshadow -Wformat -Wundef -D_GNU_SOURCE   -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -g -O2 -c -o activate.o activate.c
In file included from activate.c:33:
irqbalance.h:11:23: error: glib-unix.h: No such file or directory
make[2]: *** [activate.o] Error 1
make[2]: Leaving directory `/root/pp/irqbalance'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/pp/irqbalance'
make: *** [all] Error 2
```

glibc Version 2.22 installed .. latest from 11.4 repository.. need to check when glib-unix.h was added
```console
# zypper info glib2-devel
Loading repository data...
Reading installed packages...


Information for package glib2-devel:

Repository: SLE11-SDK-SP4-Updates
Name: glib2-devel
Version: 2.22.5-0.8.36.1
```

**Comment by dirtyharrycallahan** [comment]
I thought 11.4 went EOL March 2019?

**Comment by Pitterling** [comment]
> I thought 11.4 went EOL March 2019?

LTSS = March 2022

**Comment by nhorman** [comment]
glib-unix.h was added to glib2 about 8 years ago.  Unfortunately glib2 version 2.22.5 was tagged about prior to that file being added, which probably suggests why its not building.  You can remove the header file and hack out the use of the g_unix_* function usages if you like, or you can build the latest glib2 library for this system, and then build irqbalance.

**Comment by Pitterling** [comment]
comment out g_unix_* functions .. next error "g_list_free_full" which was added to glib2 2.28

will try the other way and get a newer glib2 for this system ...

**Comment by Pitterling** [comment]
Closing this. It was decided to retire this landscape. No follow up required. Request to SUSE for new special build glib2 @SLES11.4 revoked.

Thanks for your help and support
